# Conexión principal (usando variables de entorno)
spring.datasource.url=jdbc:postgresql://dpg-d7oa5upo3t8c73f5ure0-a.virginia-postgres.render.com/bd_prog4_villarreal
spring.datasource.username=user
spring.datasource.password=EAx0ERqaPk93WwuMqhsqc33cou4A8WbT
# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialecto para optimizar consultas a PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=ej10